server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;
    
    location / {
        try_files $uri $uri.html $uri/ /index.html;
    }
    
    location /_next/ {
        expires 30d;
        add_header Cache-Control "public, immutable";
    }
}
